### ISSUE TITLE
gcc-arm-none-eabi-5_4-2016q3-20160926以外のコンパイラでの不具合

### ISSUE THREAD

**Issue by exshonda** [spike-rt/spike-rt#6]
gcc-arm-none-eabi-5_4-2016q3-20160926以外のコンパイラでは，テストプログラム実行中に例外が発生してリセットを繰り返す．

**Comment by envzhu** [comment]
7a654c7f6c5594056c5a60511f1d3eed1db837f1 で該当のPRをマージしました
